name: Build
on:
  push:
    branches:
      - develop
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn build
