name: Build

permissions:
  contents: read

on:
  push:
    branches:
      - develop
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - run: yarn --frozen-lockfile
      - run: yarn build
