name: Create PR with release artifacts

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Create PR with artifacts
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Bump version
        id: changelog
        uses: lidofinance/conventional-changelog-action@v3
        with:
          git-message: "chore(release): {version}"
          tag-prefix: ""
          output-file: ""
          version-file: package.json
          version-path: version
          git-push: false
          skip-on-empty: false
          skip-ci: false
          create-summary: true

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: yarn --frozen-lockfile
      - run: yarn build
      - run: yarn compact
      - run: |
          mv build/index_compact.html index.html
      - run: |
          sed -i "s/MD5 (index.html) = .*$/MD5 (index.html) = $(md5sum build/index.html | cut -d ' ' -f 1)/" README.md

      - name: Create Pull Request
        uses: lidofinance/create-pull-request@v4
        if: ${{ steps.changelog.outputs.version }}
        with:
          branch: release-${{ steps.changelog.outputs.version }}
          title: "chore(release): ${{ steps.changelog.outputs.version }}"
          body: "This PR is generated automatically.\nIf you don't need this PR than close it and **delete source branch**! "
