name: Release
permissions:
  contents: write
on:
  push:
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/index.html

name: Build
on: 
  push:
    branches:
      - develop
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: 14.x  
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn build
