name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Save bundled html
        uses: actions/upload-artifact@v2
        with:
          name: Bundle
          path: build/index.html
